# Compiler settings
CXX = g++
CXXFLAGS = -Wall -Wextra -std=c++11 -g -Isrc

YACC = bison
YACCFLAGS = -d -v

LEX = flex
LEXFLAGS =

# Directories
SRC_DIR = src
BUILD_DIR = build

# Target executable
TARGET = compiler

# Source files
YACC_SRC = $(SRC_DIR)/parser.y
LEX_SRC  = $(SRC_DIR)/lexer.l
CPP_SRC  = $(SRC_DIR)/errors.cpp $(SRC_DIR)/symbol_table.cpp $(SRC_DIR)/ast.cpp $(SRC_DIR)/semantic_analyzer.cpp $(SRC_DIR)/ir_generator.cpp

# Generated files
YACC_C = $(BUILD_DIR)/parser.tab.c
YACC_H = $(BUILD_DIR)/parser.tab.h
LEX_C  = $(BUILD_DIR)/lex.yy.c

# Object files
OBJS = $(YACC_C:.c=.o) $(LEX_C:.c=.o) $(CPP_SRC:$(SRC_DIR)/%.cpp=$(BUILD_DIR)/%.o)

# Default target
all: $(TARGET)

# Build the compiler
$(TARGET): $(OBJS)
	$(CXX) $(CXXFLAGS) -o $@ $^

# Generate parser from yacc file
$(YACC_C) $(YACC_H): $(YACC_SRC)
	mkdir -p $(BUILD_DIR)
	$(YACC) $(YACCFLAGS) --defines=$(YACC_H) -o $(YACC_C) $<

# Generate lexer from lex file
$(LEX_C): $(LEX_SRC) $(YACC_H)
	$(LEX) $(LEXFLAGS) -o $(LEX_C) $<

# Compile C files generated by yacc/lex
$(BUILD_DIR)/%.o: $(BUILD_DIR)/%.c
	$(CXX) $(CXXFLAGS) -c $< -o $@

# Compile C++ files
$(BUILD_DIR)/%.o: $(SRC_DIR)/%.cpp
	mkdir -p $(BUILD_DIR)
	$(CXX) $(CXXFLAGS) -c $< -o $@

# Test with a simple program
test: $(TARGET)
	@echo "Testing simple program..."
	@echo 'int main() { return 0; }' | ./$(TARGET)

# Run all test cases
test-all: $(TARGET)
	@echo "Running all test cases..."
	@for file in testcases/*; do \
		if [ -f "$$file" ]; then \
			echo "Testing: $$file"; \
			./$(TARGET) "$$file" || echo "Failed: $$file"; \
		fi; \
	done

# Clean generated files
clean:
	rm -rf $(BUILD_DIR) $(TARGET) parser.output
	rm -rf ir_outputs logs output.3ac ast.dot ast.png *.log

# Install dependencies (for Ubuntu/Debian)
install-deps:
	@echo "Installing dependencies..."
	@sudo apt-get update
	@sudo apt-get install -y build-essential bison flex

# Install dependencies (for macOS)
install-deps-mac:
	@echo "Installing dependencies..."
	@brew install bison flex

.PHONY: all test test-all clean install-deps install-deps-mac
